#page title
page_title                                : Orgro                                     # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1512580074                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.madlonkay.orgro  # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

source_code_link                          : https://github.com/amake/orgro
support_link                              : https://github.com/amake/orgro/issues

app_icon                                  : /assets/appicon.png                       # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Orgro                                     # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : A mobile org-mode file viewer

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Aaron Madlon-Kay
your_link                                 : http://aaron.madlon-kay.com
your_city                                 : Yokohama
email_address                             : aaron+orgro@madlon-kay.com
facebook_username                         :
instagram_username                        :
twitter_username                          : amadlonkay
github_username                           : amake
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Reflowed text
    description                           : For easy viewing on mobile screens
    fontawesome_icon_name                 : mobile

  - title                                 : Syntax highlighting
    description                           : Faithfully recreates the appearance in Emacs, in both light and dark modes
    fontawesome_icon_name                 : code

  - title                                 : Reader mode
    description                           : Hide extraneous markup and show only what's important
    fontawesome_icon_name                 : book-reader

  - title                                 : Narrowing
    description                           : Narrow your view to just a single section, just like in Emacs
    fontawesome_icon_name                 : search-plus

  - title                                 : Beautiful tables
    description                           : Guaranteed correct spacing, even with non-ASCII characters
    fontawesome_icon_name                 : table

  - title                                 : Functional links
    description                           : Open external links in your web browser, and section links in narrowed views
    fontawesome_icon_name                 : link

  - title                                 : Visibility cycling
    description                           : Expand or collapse sections, blocks, and drawers just like in Emacs
    fontawesome_icon_name                 : retweet

  - title                                 : FOSS for freedom
    description                           : Get the source on GitHub for hacking or manual installation. Android users can get it on F-Droid <a href="https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6798">soon</a>.
    fontawesome_icon_name                 : hand-holding-heart

  - title                                 : Walled gardens for convenience
    description                           : Get it on the App Store or Google Play to save yourself some hassle, or to support the project
    fontawesome_icon_name                 : shopping-cart

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
